remote_theme             : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "contrast"

# Site Settings
locale                   : "en-US"
title                    : "statut.github.io"
title_separator          : "|"
name                     : "Aliaksei Statut"
description              : "My notes and developer experience"
url                      : "https://statut.github.io"
baseurl                  :
repository               : "statut/statut.github.io"
teaser                   :
words_per_minute         : 200
comments:
  provider  : "staticman_v2"
staticman:
  branch    : "master"
search                   : true
search_full_content      : true
search_provider          :
algolia:
  application_id         : "V69YKHIW6J"
  index_name             : "statut.github.io"
  search_only_api_key    : "52b3dd7f539b82833d138c657eb14c66"
  powered_by             : true
reCaptcha:
  enabled: true
  siteKey: "6LfDqU4UAAAAAMK8Ore5DgyamMM8v17Ba_r6ABv9"
  secret: "WeLQgaCijPDmHB8bwtopTHOIGqSmg/pw9Rt4RgF899gKhvedDwLnuHXSJL5oPjbajBlKPbuDE4vuj6+1KGrL2a8Cw5DLDo2aHwJzYFmvDbV6i+Ai2tAw8Rx7TKnH7mqvSLa3bWMN5sp53Ryco4XtfnGlNZ+UFLbVFaprSmomsao="

# SEO Related
google_site_verification : "5QxmhsLP5ykccj5VYO0i-7wfZIClo5qqNRazoa4zQtw"
bing_site_verification   : "8BDFAB2DE84367AF16B2B681FFFC4F6F"
yandex_site_verification : "7fe7cc2513e64266"

og_image                 : "/images/avatar.png"

# Analytics
analytics:
  provider               : "google"
  google:
    tracking_id          : "UA-116307444-1"

github: [metadata]

# Site Author
author:
  name             : "Aliaksei Statut"
  avatar           : "/images/avatar.png"
  bio              : "Software Developer"
  location         : "Vitebsk, Belarus"
  email            : "iscawn@gmail.com"
  github           : "statut"
  linkedin         : "statut"
  stackoverflow    : "3199240/statut" # "123456/username" (the last part of your profile url, e.g. http://stackoverflow.com/users/123456/username)

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Liquid
strict_front_matter: true
liquid:
  error_mode: strict

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      comments: true
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true